name: Update Token
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Replace Token
        run: |
          sed -i "s|GH_PAT_WILL_BE_HERE|${{ secrets.GH_PAT }}|g" docs/index.html
      - name: Commit
        run: |
          git config user.name "Auto"
          git config user.email "auto@github.com"
          git add .
          git commit -m "Update token" || exit 0
          git push
